Repository Lightning-AI/lightning-thunder, pull requests merged in 2024-05, with the labels that each got.

#140 Complete `torch.compile` executor
  docs/source/basic/faq.rst
  thunder/__init__.py
  thunder/benchmarks/__init__.py
  thunder/benchmarks/benchmark_litgpt.py
  thunder/benchmarks/einsum.py
  thunder/benchmarks/targets.py
  thunder/common.py
  thunder/core/rematerialization.py
  thunder/executors/nvfuserex.py
  thunder/executors/torch_compile.py
  thunder/extend/__init__.py
  thunder/tests/framework.py
  thunder/tests/test_autocast.py
  thunder/tests/test_extend.py
  thunder/tests/test_torch_compile_executor.py
Labels: documentation, enhancement, executors, torch.compile

#360 ci: drop testing with `torch~=2.2`
  .azure/docker-build.yml
  .azure/gpu-tests.yml
  .azure/notebook-runs.yml
Labels: ci, docker

#242 [benchmark] call `distributed_c10d.destroy_process_group` in benchmark_litgpt
  thunder/benchmarks/benchmark_litgpt.py
Labels: benchmarking, distributed

#380 update bwd trace ouptut name to `grad_for_<some_param>`
  thunder/executors/torch_autograd.py
Labels: developer efficiency

#381 Remove `TraceCtx.names.update` from fsdp bucketing
  thunder/distributed/transforms/fsdp.py
  thunder/executors/torch_autograd.py
Labels: distributed

#376 Add activation checkpointing to the LitGPT benchmark
  thunder/benchmarks/benchmark_litgpt.py
Labels: benchmarking

#359 FSDP as a regular transform
  thunder/__init__.py
  thunder/core/module.py
  thunder/core/transforms.py
  thunder/distributed/__init__.py
  thunder/tests/distributed/test_ddp.py
Labels: distributed, transforms

#354 Reenable vjp nvfuser ge ne le
  thunder/tests/opinfos.py
Labels: ci / tests

#384 Bumps cudnn frontend to v1.4.0
  .azure/docker-build.yml
  .azure/gpu-tests.yml
  .azure/notebook-runs.yml
  dockers/ubuntu-cuda/Dockerfile
  docs/source/fundamentals/installation.rst
Labels: documentation, ci, docker

#399 Fix flaky test_prim_inplace_copy_fwd
  thunder/tests/test_inplace_copy.py
Labels: ci / tests

#408 ci: fix trigger event for docs' check
  .github/workflows/docs-build.yml
Labels: ci

#364 Update "phantom grad" to use the same forward-backward transformation code as "vjp"
  thunder/benchmarks/__init__.py
  thunder/benchmarks/targets.py
  thunder/core/transforms.py
  thunder/core/utils.py
  thunder/tests/test_grad.py
Labels: autograd, transforms

#400 Switches to cudnn-frontend pypi package
  .azure/docker-build.yml
  dockers/ubuntu-cuda/Dockerfile
  docs/source/fundamentals/installation.rst
Labels: documentation, ci, docker

#285 Add sanity check for inplace copy
  thunder/__init__.py
  thunder/core/transform_common.py
  thunder/tests/test_inplace_copy.py
Labels: aliasing

#245 [docs] add some classes/methods, fix ref, fix `no_sync` equations
  docs/source/conf.py
  docs/source/index.rst
  docs/source/reference/common/index.rst
  docs/source/reference/extend/index.rst
  thunder/__init__.py
  thunder/common.py
  thunder/core/module.py
  thunder/distributed/__init__.py
Labels: documentation

#424 [fsdp] Propagate `bucketing_strategy` and `sharding_strategy` via original module
  thunder/distributed/__init__.py
  thunder/distributed/transforms/fsdp.py
  thunder/distributed/transforms/fsdp_v2.py
  thunder/executors/torch_autograd.py
  thunder/tests/distributed/test_ddp.py
Labels: distributed

#415 [fsdp] Coping with params whose `shape[0]` is not divisible by `world_size` by padding
  thunder/core/jit_ext.py
  thunder/core/proxies.py
  thunder/distributed/__init__.py
  thunder/distributed/prims.py
  thunder/tests/distributed/test_ddp.py
Labels: distributed

#286 Number proxies is not a number
  thunder/clang/__init__.py
  thunder/clang/langctx.py
  thunder/core/baseutils.py
  thunder/core/prims.py
  thunder/core/proxies.py
  thunder/core/transforms.py
  thunder/core/utils.py
  thunder/executors/nvfuserex_impl.py
  thunder/executors/pythonex.py
  thunder/executors/torchex.py
  thunder/tests/test_nvfuser_remat.py
  thunder/torch/__init__.py
  thunder/torch/langctx.py
Labels: dynamic constraints

#293 test_phantom_grad: support ops which return non-differentiable outputs
  thunder/tests/opinfos.py
  thunder/tests/test_grad.py
Labels: testing

#442 [benchmark] get rid of a function of fwd-bwd
  thunder/benchmarks/benchmark_litgpt.py
  thunder/executors/torch_autograd.py
Labels: benchmarking

#459 pad: support alternate `value` types.
  thunder/tests/test_shape_ops.py
  thunder/torch/__init__.py
Labels: nemo

#383 Fix `sort_waits` to move `wait` closer to its consumer (#277)
  thunder/distributed/utils.py
  thunder/executors/torch_autograd.py
Labels: distributed

#479 Update split QKV + RoPE benchmark
  thunder/benchmarks/targets.py
Labels: benchmarking

#489 Add "important configs" to the benchmarks/targets.py as the default list for parametrized benchmarks
  thunder/benchmarks/targets.py
Labels: benchmarking

#491 Use PyTorch Benchmarking Timer by default with pytest-benchmark
  pyproject.toml
  requirements/test.txt
  thunder/benchmarks/einsum.py
  thunder/benchmarks/targets.py
Labels: dependencies, install, benchmarking

#222 Move Grad AllReduce Bucketing to inside of `thunder.executors.passes.transform_for_execution` from `torch_autograd.split_forward_backward`
  thunder/distributed/prims.py
  thunder/distributed/transforms/__init__.py
  thunder/distributed/transforms/ddp.py
  thunder/executors/passes.py
  thunder/executors/torch_autograd.py
Labels: distributed

#494 Let pytest-benchmark figure out required number of rounds
  thunder/benchmarks/__init__.py
  thunder/benchmarks/targets.py
Labels: benchmarking

#496 drop standalone testing in favour of plain pytest-3 for distributed
  .azure/gpu-tests.yml
  .github/workflows/ci-testing.yml
  scripts/run_standalone_tests.sh
Labels: ci

#410 [distributed][Tensor Parallelism] Implement early transforms for column-wise and row-wise linear and embedding
  docs/source/reference/distributed/index.rst
  notebooks/dev_tutorials/fsdp_tutorial.ipynb
  thunder/common.py
  thunder/core/jit_ext.py
  thunder/core/proxies.py
  thunder/distributed/__init__.py
  thunder/distributed/prims.py
  thunder/distributed/tensor_parallel/__init__.py
  thunder/distributed/tensor_parallel/column_wise.py
  thunder/distributed/tensor_parallel/common.py
  thunder/distributed/tensor_parallel/row_wise.py
  thunder/distributed/transforms/fsdp_v2.py
  thunder/executors/torchex.py
  thunder/tests/distributed/helper.py
  thunder/tests/distributed/test_checkpoint.py
  thunder/tests/distributed/test_ddp.py
  thunder/tests/distributed/test_tensor_parallel.py
  thunder/torch/__init__.py
Labels: documentation, distributed
