Repository Lightning-AI/lightning-thunder, pull requests merged in 2024-07, with the labels that each got.

#708 launch tests with cuda_launch_blocking
  .azure/gpu-tests.yml
Labels: ci

#715 pin optree
  requirements/base.txt
Labels: dependencies

#716 `namespace` became keyword only in 0.12.0
  requirements/base.txt
  thunder/core/pytree.py
Labels: dependencies

#695 TransformerEngine - Intermediate tensor sharding
  thunder/executors/transformer_engineex.py
  thunder/tests/distributed/test_ddp.py
Labels: distributed, TransformerEngine

#744 Remove some nanoGPT cases from benchmarks/targets.py, they are replaced by LitGPT
  thunder/benchmarks/__init__.py
  thunder/benchmarks/targets.py
Labels: benchmarking

#749 [in-place] Improve how to collect necessary `prims.copy_` to function args/kwargs
  docs/source/reference/core/index.rst
  docs/source/reference/core/transform_common.rst
  thunder/core/transform_common.py
  thunder/tests/test_inplace_functionalization.py
Labels: documentation

#762 add implicit pytorch dev depends
  dockers/ubuntu-cuda/Dockerfile
Labels: docker, ci

#822 bump pytorch min ver to 2.3 and macos runners to m1
  .github/workflows/ci-testing.yml
  requirements/base.txt
Labels: dependencies, ci

#829 Fix HF bert recursive error
  requirements/test.txt
  thunder/core/codeutils.py
  thunder/tests/test_networks.py
Labels: dependencies

#767 starting 3.12 compat, enable test_interpreter CI run for 3.12
  .github/workflows/ci-testing.yml
  setup.py
  thunder/core/interpreter.py
  thunder/tests/test_interpreter.py
Labels: install, ci

#855 CUDAGraphs: fix issues with buffer initializations
  thunder/executors/cudagraphex.py
  thunder/extend/__init__.py
  thunder/tests/test_cudagraphs_executor.py
  thunder/tests/test_extend.py
Labels: cudagraphs

#847 bump to pytorch 2.3.1
  .azure/docker-build.yml
  .azure/notebook-runs.yml
Labels: docker, ci

#854 Add benchmarking to the docs
  docs/source/index.rst
  docs/source/intermediate/benchmarking.rst
Labels: documentation

#881 Fix outdated comments.
  .azure/gpu-tests.yml
  thunder/benchmarks/__init__.py
Labels: ci
