Repository Lightning-AI/lightning-thunder, pull requests merged in 2024-03, with the labels that each got.

#20 Link to LitGPT for the Thunder example
  README.md
  examples/lit-gpt/.gitignore
  examples/lit-gpt/1_forward.py
  examples/lit-gpt/README.md
  examples/lit-gpt/_ddp_thunder.py
  examples/lit-gpt/_fsdp_thunder.py
  examples/lit-gpt/test_ddp_thunder.py
  examples/lit-gpt/test_fsdp_thunder.py
  examples/lit-gpt/train.py
  examples/lit-gpt/train_fsdp.py
  requirements/test.txt
  thunder/benchmarks/test_benchmark_litgpt.py
Labels: dependencies

#8 ci: deploy docs via GCP
  .github/workflows/docs-build.yml
Labels: ci

#9 ci: enable upload codecov statistics
  .azure/gpu-tests.yml
  .github/workflows/ci-testing.yml
Labels: ci

#39 docs: fix rendering of math equations
  .github/workflows/docs-build.yml
  docs/source/conf.py
Labels: documentation, ci

#44 Add dark and light mode thunder branding
  docs/source/_static/images/LightningThunderDarkModewByline.png
  docs/source/_static/images/LightningThunderLightModewByline.png
Labels: documentation

#49 docs: optimize images for web size
  .pre-commit-config.yaml
  docs/source/_static/images/normalized_training_throughput_zero2.png
  docs/source/_static/images/training_throughput_single.png
Labels: documentation

#37 Update LitGPT pin
  notebooks/dev_tutorials/fsdp_tutorial.ipynb
  notebooks/zero_to_thunder.ipynb
  requirements/notebooks.txt
  requirements/test.txt
  thunder/benchmarks/__init__.py
  thunder/benchmarks/benchmark_litgpt.py
  thunder/benchmarks/distributed.py
  thunder/benchmarks/targets.py
  thunder/tests/litgpt_model.py
  thunder/tests/test_interpreter.py
  thunder/tests/test_jit_general.py
Labels: dependencies

#26 docker: pip install nvFuser for Torch wheels (PR2469)
  dockers/ubuntu-cuda/Dockerfile
Labels: ci, docker

#56 gh: collapse checks in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ci

#61 add Carlos to codeowners
  .github/CODEOWNERS
Labels: ci

#63 A follow-up cleanup on #57.
  thunder/executors/cudnnex.py
Labels: cudnn

#66 bump litGPT to `940ffc96f7214bca24aa77479bc7c33900aaef28`
  requirements/notebooks.txt
  requirements/test.txt
Labels: dependencies

#65 ci: force sanity check to be strict
  .azure/gpu-tests.yml
  .azure/sanity-check.sh
Labels: ci

#73 Update cc-bot issue number
  .github/lightning-probot.yml
Labels: ci

#71 Add custom CUDA kernels to README
  README.md
  pyproject.toml
Labels: install

#36 bumps cudnnex to 1.2.1 (PR2485)
  .azure/docker-build.yml
  .azure/gpu-tests.yml
  dockers/ubuntu-cuda/Dockerfile
  docs/source/fundamentals/installation.rst
Labels: documentation, ci, docker, cudnn

#55 docs: switch to use LAI sphinx template
  .github/workflows/docs-build.yml
  Makefile
  docs/source/conf.py
  requirements/docs.txt
Labels: documentation, ci, dependencies

#27 docker: building with Apex (PR2455)
  .azure/docker-build.yml
  .azure/gpu-tests.yml
  .azure/notebook-runs.yml
  dockers/ubuntu-cuda/Dockerfile
  notebooks/.ignore.ci
  thunder/tests/test_apex_executor.py
Labels: ci, docker

#59 Allocate dQ, dK, and dV as a catted tensor to save a downstream cat in nvFuser.
  thunder/executors/cudnnex.py
  thunder/executors/nvfuserex_impl.py
  thunder/tests/test_cudnn_executor.py
Labels: enhancement, cudnn

#99 ci: fix not failing step if tests failed
  .azure/gpu-tests.yml
Labels: ci

#86 ci: testing with `torch==2.3` /test and move `2.4` /nightly
  .azure/docker-build.yml
  .azure/gpu-tests.yml
  dockers/ubuntu-cuda/Dockerfile
Labels: ci, docker

#89 update codeowners for ci/cd
  .github/CODEOWNERS
Labels: ci
