Repository Lightning-AI/lightning-thunder, pull requests merged in 2024-06, with the labels that each got.

#498 Update benchmarks/targets.py: inference/forward/backward parametrization
  thunder/benchmarks/__init__.py
  thunder/benchmarks/targets.py
Labels: benchmarking

#511 TE: Disable support for version less than v1.6
  thunder/executors/transformer_engineex.py
  thunder/tests/distributed/test_ddp.py
Labels: TransformerEngine

#515 TE: Support v1.8 - current main
  thunder/executors/transformer_engineex.py
Labels: TransformerEngine

#522 Add docs for timer_and_memory_stats in benchmarks/targets.py
  thunder/benchmarks/targets.py
Labels: benchmarking

#517 fixing pythonex operators
  thunder/executors/pythonex.py
  thunder/tests/test_pythonex.py
Labels: symbolic values

#512 Enable TORCH_NCCL_AVOID_RECORD_STREAMS=1 by default
  thunder/benchmarks/benchmark_litgpt.py
  thunder/distributed/__init__.py
  thunder/distributed/tensor_parallel/column_wise.py
  thunder/distributed/tensor_parallel/row_wise.py
Labels: cuda

#534 [Tensor Parallelism] fix shape of output tensor proxy's given off from tensor parallel ops
  thunder/distributed/tensor_parallel/common.py
  thunder/tests/distributed/modules.py
  thunder/tests/distributed/test_tensor_parallel.py
Labels: tensor parallel

#547 fix cudnn frontend version in docker build
  .azure/docker-build.yml
Labels: ci, docker

#553 Modify subsymbols in cse_single_bsym; unblocks phi-2 with inductor_cat+nvfuser executors
  thunder/core/transform_common.py
  thunder/tests/test_torch_compile_executor.py
Labels: optimization passes

#559 Ignore checkpoint_activations for Thunder in benchmark_litgpt.py
  thunder/benchmarks/benchmark_litgpt.py
Labels: benchmarking

#563 [Tensor Parallelism] Allow modules on meta device
  thunder/distributed/tensor_parallel/column_wise.py
  thunder/distributed/tensor_parallel/row_wise.py
  thunder/tests/distributed/test_tensor_parallel.py
Labels: tensor parallel

#577 [Tensor Parallel] flatten `new_out` when updating `swap_map`
  thunder/distributed/tensor_parallel/common.py
  thunder/tests/distributed/test_tensor_parallel.py
Labels: tensor parallel

#572 Added `torch.baddbmm` operator
  thunder/executors/torchex.py
  thunder/tests/opinfos.py
  thunder/torch/__init__.py
Labels: operators, nemo

#591 TE: fix the placement of bwd_sync symbol in trace
  thunder/executors/transformer_engineex.py
  thunder/tests/distributed/test_ddp.py
Labels: TransformerEngine

#596 Restore usage of CUDAGraphExecutor with compiled backward function
  thunder/__init__.py
  thunder/executors/torch_autograd.py
Labels: cudagraphs

#617 fix numpy version for tests
  requirements/notebooks.txt
  requirements/test.txt
Labels: dependencies

#586 adding Static Constraint field in NumberProxy
  thunder/core/jit_ext.py
  thunder/core/prims.py
  thunder/core/proxies.py
  thunder/core/utils.py
  thunder/tests/test_jit_general.py
Labels: dynamic constraints

#561 add quantization transform
  requirements/test.txt
  thunder/__init__.py
  thunder/core/module.py
  thunder/core/transform_common.py
  thunder/tests/test_networks.py
  thunder/transforms/quantization.py
  thunder/transforms/utils.py
Labels: dependencies

#631 Remove robieta from CODEOWNERS
  .github/CODEOWNERS
Labels: ci

#613 Allowing static constraint in torch/__init__.py
  thunder/core/prims.py
  thunder/core/proxies.py
  thunder/executors/pythonex.py
  thunder/tests/test_jit_general.py
  thunder/torch/__init__.py
Labels: dynamic constraints

#651 Bumps cudnn FE to v1.5.2
  .azure/docker-build.yml
  .azure/gpu-tests.yml
  .azure/notebook-runs.yml
  dockers/ubuntu-cuda/Dockerfile
  thunder/executors/cudnnex.py
Labels: docker, ci

#663 bump: ci check versions
  .github/workflows/ci-checks.yml
Labels: ci
