Repository Lightning-AI/lightning-thunder, pull requests merged in 2024-04, with the labels that each got.

#84 Add FAQ to docs
  docs/source/basic/faq.rst
  docs/source/index.rst
Labels: documentation

#136 Added support for `torch.Tensor.unfold`
  thunder/clang/__init__.py
  thunder/core/prims.py
  thunder/executors/torchex.py
  thunder/tests/opinfos.py
  thunder/torch/__init__.py
Labels: operators

#115 Support and surface `(print_)last_interpreter_log()` to the public API, introduce `TraceResults`
  docs/source/reference/thunder.rst
  thunder/__init__.py
  thunder/common.py
  thunder/core/interpreter.py
  thunder/core/jit_ext.py
  thunder/core/trace.py
  thunder/core/transforms.py
  thunder/functional.py
  thunder/tests/test_core.py
  thunder/tests/test_interpreter.py
Labels: documentation

#155 docker: bump Triton 2.3 for PT 2.3
  .azure/docker-build.yml
Labels: ci, docker

#103 [test_ddp][fsdp] check strategy before check pack arg's size
  .azure/gpu-tests.yml
  thunder/distributed/__init__.py
  thunder/tests/distributed/test_ddp.py
Labels: ci

#153 Bumps cudnn frontend to v1.3.0
  .azure/docker-build.yml
  .azure/gpu-tests.yml
  .azure/notebook-runs.yml
  dockers/ubuntu-cuda/Dockerfile
  docs/source/fundamentals/installation.rst
Labels: documentation, ci, docker

#167 add cuda-python extension demo
  .pre-commit-config.yaml
  docs/source/index.rst
  notebooks/extend_thunder_with_cuda_python.ipynb
  requirements/notebooks.txt
Labels: documentation, dependencies

#166 Minor changes to the benchmark litgpt script
  thunder/benchmarks/benchmark_litgpt.py
Labels: benchmarking

#149 add docs about adding ops to thunder
  docs/source/advanced/contrib_thunder.rst
  docs/source/index.rst
Labels: documentation

#165 Bumps stable torch to `2.2.2`
  .azure/docker-build.yml
  .azure/gpu-tests.yml
  .azure/notebook-runs.yml
Labels: ci, docker

#157 Add memory_format in torch.Tensor.to
  thunder/executors/torchex.py
  thunder/tests/test_core.py
  thunder/torch/__init__.py
Labels: visionmodel

#182 Improve batch_norm backward performance for automatically generated backward
  thunder/core/transforms.py
  thunder/torch/__init__.py
Labels: autograd, nvfuser

#188 Remove thunder_backward; it became obsolete with new thunder.jit() code
  docs/source/reference/executors/torchex.rst
  thunder/__init__.py
  thunder/common.py
  thunder/executors/torch_autograd.py
  thunder/tests/framework.py
  thunder/tests/test_grad.py
Labels: documentation, triage review, autograd

#181 add cuda method
  thunder/tests/opinfos.py
  thunder/tests/test_grad.py
  thunder/torch/__init__.py
Labels: operators

#201 skip checking github links to pytorch
  docs/source/conf.py
Labels: documentation

#215 Only downloads cudnn in docker images when doing torch source builds
  dockers/ubuntu-cuda/Dockerfile
Labels: ci, docker

#48 te executor: auto enable fp8_autocast ctx manager (PR2190)
  thunder/benchmarks/benchmark_litgpt.py
  thunder/core/trace.py
  thunder/executors/torch_autograd.py
  thunder/executors/transformer_engineex.py
  thunder/tests/distributed/test_ddp.py
  thunder/tests/test_transformer_engine_executor.py
Labels: TransformerEngine

#236 ci/docs: set Sphinx public theme as alternative
  .github/workflows/docs-build.yml
  Makefile
  docs/source/conf.py
  requirements/docs.txt
Labels: documentation, ci, dependencies

#238 autograd: add executor to cache key for make_aug_forward_and_backward
  thunder/core/transforms.py
  thunder/core/vjp_utils.py
  thunder/tests/test_grad.py
Labels: bug, autograd

#142 TransformerEngine : Add test with FSDP (and updates to `ddp_wrapper` in test_ddp.py)
  thunder/tests/distributed/test_ddp.py
Labels: distributed, TransformerEngine

#274 Install `litgpt` from pypi
  requirements/test.txt
Labels: dependencies
