Repository Lightning-AI/lightning-thunder, pull requests merged in 2024-11, with the labels that each got.

#1268 Add an nvtx decorator for annotating components
  thunder/core/profile.py
  thunder/tests/test_core.py
Labels: profiling

#1403 Bump liger to 0.4.0
  requirements/notebooks.txt
Labels: dependencies

#1430 fix(ci): resolve using PT nightly
  .github/workflows/ci-testing.yml
Labels: ci

#1406 Test HF's implementation of Qwen 2 model
  thunder/tests/test_networks.py
Labels: huggingface

#1433 use official nightly url
  .github/workflows/ci-testing.yml
Labels: ci

#1416 Reduce CPU overhead of FusionDefinitionWrapper
  thunder/executors/nvfuserex_impl.py
Labels: nvfuser

#1271 Improve no_autocast overhead from 3.1 µs to 0.5 µs (6x improvement)
  thunder/executors/torchex.py
  thunder/tests/test_autocast.py
Labels: performance

#1439 Test HF's implementation of Phi 3 model
  requirements/test.txt
  thunder/tests/test_networks.py
Labels: dependencies, huggingface

#1448 update codeowners
  .github/CODEOWNERS
Labels: ci

#1447 add extensible DebugOptions class
  docs/source/reference/thunder.rst
  thunder/__init__.py
  thunder/common.py
  thunder/core/jit_ext.py
  thunder/core/options.py
  thunder/tests/test_core.py
Labels: documentation

#1380 ThunderFX: Save the reproducer script into files
  thunder/core/transform_common.py
  thunder/dynamo/compiler.py
  thunder/dynamo/compiler_graph_benchmark.py
  thunder/dynamo/splitter.py
  thunder/dynamo/utils.py
  thunder/tests/test_dynamo.py
Labels: developer efficiency, thunderfx

#1481 Register grad for torch.Tensor.item
  thunder/tests/test_grad.py
  thunder/torch/__init__.py
Labels: autograd
