Repository Lightning-AI/lightning-thunder, pull requests merged in 2024-12, with the labels that each got.

#1480 Add output node if it does not exist in the split module
  thunder/dynamo/splitter.py
  thunder/tests/test_dynamo.py
Labels: thunderfx

#1450 support dynamic getitem in dictionary for symbolic values
  thunder/core/interpreter.py
  thunder/tests/test_jit_general.py
Labels: dynamic constraints

#1466 [docs] `thunder.transforms.ConstantFolding`
  docs/source/reference/transforms/index.rst
  thunder/transforms/__init__.py
  thunder/transforms/constant_folding.py
Labels: documentation

#1508 group all GHActions updates to single PR
  .github/dependabot.yml
Labels: ci

#1524 Notebook: ThunderFX tutorial
  docs/source/index.rst
  notebooks/hello_world_thunderfx.ipynb
Labels: documentation

#1559 [nvfuser] don't allow shape only nvfuser region
  thunder/core/prims.py
  thunder/executors/nvfuserex_impl.py
  thunder/tests/test_networks.py
  thunder/tests/test_nvfuser.py
Labels: nvfuser
