Repository Lightning-AI/lightning-thunder, pull requests merged in 2024-08, with the labels that each got.

#713 Group saved for backward tensors produced by TransfomerEngine together with all other saved for backward tensors
  thunder/executors/transformer_engineex.py
  thunder/tests/test_transformer_engine_executor.py
Labels: autograd, TransformerEngine

#798 Error out if alias tensor args are consumed by in-place ops
  thunder/__init__.py
  thunder/core/proxies.py
  thunder/core/transform_common.py
  thunder/tests/test_inplace_functionalization.py
Labels: in-place

#910 add lapack to build
  dockers/ubuntu-cuda/Dockerfile
Labels: docker, ci

#899 improve fusion stability
  requirements/base.txt
  thunder/core/pytree.py
  thunder/core/rematerialization.py
  thunder/core/transform_common.py
  thunder/core/utils.py
  thunder/executors/cudagraphex.py
  thunder/executors/data_dependent_partition.py
  thunder/executors/nvfuserex_impl.py
  thunder/executors/torch_compile.py
  thunder/executors/utils.py
  thunder/tests/test_core.py
  thunder/tests/test_nvfuser.py
Labels: dependencies

#911 Support parameters requiring padding in `fsdp(jit(model, ...), ...)`
  thunder/distributed/transforms/fsdp_v2.py
  thunder/tests/distributed/test_fsdp.py
Labels: distributed

#869 track base and views for better in-place modification propagation
  thunder/core/transform_common.py
  thunder/tests/test_inplace_functionalization.py
  thunder/torch/__init__.py
Labels: in-place

#873 DDP as a transform
  thunder/distributed/__init__.py
  thunder/distributed/transforms/ddp_v2.py
  thunder/tests/distributed/test_ddp.py
Labels: distributed

#922 add brief docstring to `MaterializationTransform`
  docs/source/index.rst
  docs/source/reference/transforms/index.rst
  thunder/transforms/__init__.py
  thunder/transforms/materialization.py
Labels: documentation

#894 Add nvFuser fusion region repro util and update DebugTransform
  docs/source/basic/inspecting_traces.rst
  thunder/core/transforms.py
  thunder/dev_utils/debug_transform.py
  thunder/examine/__init__.py
  thunder/executors/nvfuserex_impl.py
Labels: documentation, debugging, nvfuser

#699 TE: add benchmark in targets.py
  thunder/benchmarks/__init__.py
  thunder/benchmarks/targets.py
Labels: TransformerEngine

#882 Add executor for flash attention 3
  thunder/executors/fa3ex.py
  thunder/extend/__init__.py
  thunder/tests/test_extend.py
  thunder/tests/test_fa3_executor.py
Labels: executors

#877 in-place ops to alias tensor args of function
  docs/source/reference/core/functionalization.rst
  docs/source/reference/core/index.rst
  docs/source/reference/core/transform_common.rst
  thunder/__init__.py
  thunder/core/functionalization.py
  thunder/core/transform_common.py
  thunder/tests/test_inplace_functionalization.py
Labels: documentation

#926 Add get_saved_for_backward_tensors
  thunder/core/vjp_utils.py
  thunder/executors/torch_autograd.py
  thunder/tests/test_grad.py
Labels: developer efficiency

#942 Make `TraceCtx` objects pickleable with `dill`
  requirements/base.txt
  thunder/core/prims.py
  thunder/core/symbol.py
  thunder/tests/test_core.py
Labels: dependencies

#937 fix - TransformerEngine with FSDP Bucketing
  thunder/executors/torch_autograd.py
  thunder/tests/distributed/test_fsdp.py
Labels: TransformerEngine

#947 Add Thunder as a Dynamo backend
  thunder/benchmarks/benchmark_litgpt.py
  thunder/dynamo/__init__.py
  thunder/dynamo/compiler.py
  thunder/tests/framework.py
  thunder/tests/test_dynamo.py
  thunder/tests/test_networks.py
Labels: dynamo

#938 support apex fused_rms_norm
  docs/source/intermediate/additional_executors.rst
  docs/source/reference/executors/apexex.rst
  docs/source/reference/executors/index.rst
  notebooks/dev_tutorials/extend.ipynb
  thunder/benchmarks/__init__.py
  thunder/core/pytree.py
  thunder/executors/apex_entropyex_impl.py
  thunder/executors/apex_fused_rms_norm_impl.py
  thunder/executors/apexex.py
  thunder/executors/transformer_engineex.py
  thunder/executors/utils.py
  thunder/extend/__init__.py
  thunder/tests/test_apex_cross_entropy_executor.py
  thunder/tests/test_apex_fused_norms.py
Labels: documentation

#973 Better error for the mismatch in the number of outputs between forward and an augmented forward
  thunder/core/transforms.py
  thunder/core/vjp_utils.py
  thunder/tests/test_grad.py
Labels: autograd

#968 initial version of state_dict() / load_state_dict() with override compatibility
  docs/source/reference/thunder.rst
  thunder/core/module.py
  thunder/tests/test_core.py
  thunder/tests/test_networks.py
  thunder/tests/test_transforms.py
  thunder/transforms/materialization.py
Labels: documentation

#974 Add Inductor (torch.compile) concatenation executor to the default list of executors
  thunder/__init__.py
  thunder/executors/torch_compile.py
  thunder/tests/test_torch_compile_executor.py
Labels: executors, torch.compile

#975 more pickling
  requirements/base.txt
  thunder/core/devices.py
  thunder/core/dtypes.py
  thunder/tests/test_core.py
Labels: dependencies

#999 Use pytorch 2.3.1 based containers
  .azure/gpu-tests.yml
Labels: ci

#977 make cudagraphs a transform
  thunder/__init__.py
  thunder/benchmarks/__init__.py
  thunder/common.py
  thunder/extend/__init__.py
  thunder/tests/test_cudagraphs_executor.py
  thunder/tests/test_extend.py
  thunder/tests/test_networks.py
  thunder/tests/test_transforms.py
  thunder/transforms/cudagraph.py
Labels: cudagraphs

#1002 benchmark_litgpt.py: Start building executors list from the default ones
  thunder/benchmarks/benchmark_litgpt.py
Labels: benchmarking

#985 update nvfuser install instructions
  README.md
  docs/source/fundamentals/installation.rst
Labels: documentation

#1006 benchmark_litgpt.py: fix executors to be a list; fix the order of executors for sdpa
  thunder/benchmarks/benchmark_litgpt.py
Labels: benchmarking

#966 Trace Transformation Tutorial - CPU Offloading
  docs/source/index.rst
  notebooks/writing_a_trace_transform_cpu_offloading.ipynb
Labels: documentation

#1019 Improve memory usage for stablecode-completion-alpha-3b
  thunder/executors/torch_compile.py
Labels: torch.compile, memory use

#731 Disable bookend by default.
  thunder/executors/nvfuserex_impl.py
  thunder/tests/framework.py
  thunder/tests/test_examine_memory.py
  thunder/tests/test_inplace_functionalization.py
  thunder/tests/test_nvfuser_remat.py
Labels: nvfuser
