Repository Lightning-AI/lightning-thunder, pull requests merged in 2024-09, with the labels that each got.

#1089 [CI Fix] Update check-package to v0.11.7
  .github/workflows/ci-checks.yml
Labels: ci

#1090 Remove thunder+nvfuser+torch.compile executor from default list in targets.py
  thunder/benchmarks/targets.py
Labels: benchmarking

#451 Add resnet50 benchmark (#443)
  thunder/benchmarks/__init__.py
  thunder/benchmarks/targets.py
Labels: benchmarking, visionmodel

#1088 bump pytorch/triton to 2.4/3.0.0
  .azure/docker-build.yml
Labels: docker, ci

#1100 switch ci jobs to 2.4
  .azure/gpu-tests.yml
  .azure/notebook-runs.yml
Labels: ci

#1105 Add a parametrized benchmark for swiglu
  thunder/benchmarks/__init__.py
  thunder/benchmarks/targets.py
Labels: benchmarking

#1112 Remove redundant parametrizations for swiglu benchmark
  thunder/benchmarks/targets.py
Labels: benchmarking

#1114 Remove thunder.compile and tests
  .github/workflows/ci-testing.yml
  thunder/__init__.py
  thunder/common.py
  thunder/executors/torchex.py
  thunder/tests/framework.py
  thunder/tests/opinfos.py
  thunder/tests/test_apex_cross_entropy_executor.py
  thunder/tests/test_autocast.py
  thunder/tests/test_core.py
  thunder/tests/test_cudnn_executor.py
  thunder/tests/test_grad.py
  thunder/tests/test_nvfuser.py
  thunder/tests/test_nvfuser_remat.py
  thunder/torch/__init__.py
Labels: ci

#1115 Remove interpreter-based identity transform
  thunder/core/transforms.py
  thunder/tests/test_core.py
Labels: transforms

#1118 Move autocast from thunder.core.transforms to thunder.transforms
  thunder/common.py
  thunder/core/symbol.py
  thunder/core/transforms.py
  thunder/tests/test_autocast.py
  thunder/tests/test_core.py
  thunder/tests/test_transformer_engine_executor.py
  thunder/torch/__init__.py
  thunder/transforms/autocast.py
Labels: transforms, autocast

#1116 Remove interpreter-based vmap transform
  thunder/core/transforms.py
  thunder/tests/test_core.py
Labels: transforms

#1117 Remove interpreter-based jvp transform
  thunder/core/transforms.py
  thunder/tests/opinfos.py
  thunder/tests/test_core.py
  thunder/tests/test_grad.py
Labels: transforms

#1119 Move eval_trace from transforms.py and rename it to interpret_trace
  thunder/core/trace_interpreter.py
  thunder/core/transforms.py
  thunder/tests/test_grad.py
Labels: tracing architecture

#1120 remove functional jit
  docs/source/index.rst
  docs/source/reference/thunder.rst
  notebooks/functional_jit.ipynb
  thunder/__init__.py
  thunder/clang/__init__.py
  thunder/core/jit_ext.py
  thunder/core/options.py
  thunder/functional.py
  thunder/tests/test_auto_register_torchops.py
  thunder/tests/test_core.py
  thunder/tests/test_jit_functional.py
  thunder/tests/test_jit_general.py
  thunder/tests/test_nvfuser.py
  thunder/tests/test_ops.py
Labels: documentation

#1094 thunder + dynamo : use recompile instead of real_recompile
  thunder/dynamo/compiler.py
  thunder/tests/test_dynamo.py
Labels: dynamo+thunder

#1075 thunder as torch.compile backend - Add `splitter` to pass unsupported regions to inductor
  thunder/dynamo/compiler.py
  thunder/dynamo/splitter.py
  thunder/dynamo/utils.py
  thunder/tests/test_dynamo.py
Labels: dynamo, dynamo+thunder

#1157 TE - fix - removal of with_transpose argument
  thunder/executors/transformer_engineex.py
  thunder/tests/distributed/test_ddp.py
  thunder/tests/distributed/test_fsdp.py
Labels: TransformerEngine

#1159 thunder + dynamo : consider methods which are only registered to torchctx language context
  thunder/dynamo/utils.py
  thunder/tests/test_dynamo.py
Labels: dynamo+thunder

#1170 Fix leak related to stop iteration
  .github/workflows/ci-testing.yml
  thunder/core/interpreter.py
  thunder/tests/test_interpreter.py
Labels: ci

#1027 allow NumberProxy in TensorProxy._shape for `symbolic values` cache policy
  thunder/clang/__init__.py
  thunder/core/baseutils.py
  thunder/core/jit_ext.py
  thunder/core/prims.py
  thunder/core/proxies.py
  thunder/executors/nvfuserex_impl.py
  thunder/executors/pythonex.py
  thunder/tests/test_jit_general.py
Labels: dynamic constraints
