Repository Lightning-AI/lightning-thunder, pull requests merged in 2025-01, with the labels that each got.

#1596 Error out when specified name for Proxy creation is already used
  thunder/core/jit_ext.py
  thunder/core/proxies.py
  thunder/core/trace.py
  thunder/tests/test_core.py
Labels: tracing architecture

#1600 TE: fix failing intermediate sharding test
  thunder/executors/torch_autograd.py
Labels: autograd, TransformerEngine

#1625 TE: disable recomputing in backward
  thunder/core/prims.py
  thunder/core/transforms.py
  thunder/executors/transformer_engineex.py
Labels: TransformerEngine

#1626 TE: avoid proxy name clash
  thunder/core/proxies.py
  thunder/executors/transformer_engineex.py
Labels: TransformerEngine

#1639 split GPU CI jobs
  .azure/gpu-tests.yml
  docs/.readthedocs.yaml
Labels: documentation, ci

#1645 split ops and grads on CPU, parallel for test_interpreter
  .github/workflows/ci-testing.yml
Labels: ci

#1458 Raise when in place operations occur on leafs requiring grad
  thunder/core/functionalization.py
  thunder/core/prims.py
  thunder/core/transforms.py
  thunder/executors/nvfuserex_impl.py
  thunder/executors/torchex.py
  thunder/tests/test_core.py
  thunder/tests/test_inplace_copy.py
  thunder/tests/test_inplace_functionalization.py
  thunder/torch/__init__.py
Labels: autograd, in-place

#1653 bump: `Lightning-AI/utilities` to use `main`
  .github/workflows/ci-checks.yml
Labels: ci

#1660 Add an option to be able to disable replace_uniform
  thunder/core/rematerialization.py
Labels: randomness

#1528 [litgpt benchmark] enable `force_recompute_fp8_weight_in_bwd` when `torchao.float8` is used with FSDP2
  thunder/benchmarks/benchmark_litgpt.py
Labels: benchmarking

#1597 Make TensorProxy requires_grad argument to be False by default
  thunder/core/proxies.py
  thunder/tests/test_core.py
Labels: tracing architecture

#1419 Add a Notebook about Trace, BoundSymbol, Symbol and Proxy
  docs/source/index.rst
  notebooks/thunder_trace_intro.ipynb
  pyproject.toml
Labels: documentation, install

#1668 make jit testing parallel for Python 3.11 and 3.12
  .github/workflows/ci-testing.yml
Labels: ci

#1685 Add clone -> fd.ops.set translation for nvFuser
  thunder/executors/nvfuserex_impl.py
  thunder/tests/test_networks.py
Labels: nvfuser

#1709 pin check schema
  .github/workflows/ci-checks.yml
Labels: ci

#1698 bump transformers version
  requirements/test.txt
  thunder/tests/test_networks.py
Labels: dependencies
