Repository Lightning-AI/lightning-thunder, pull requests merged in 2025-02, with the labels that each got.

#1715 Use context manager to set priority for the sdp attention backends
  thunder/benchmarks/benchmark_litgpt.py
Labels: benchmarking

#1753 thunderFX - fix leak caused due to holding exception object
  thunder/dynamo/utils.py
  thunder/tests/test_dynamo.py
Labels: thunderfx

#1720 Add HF benchmarks
  thunder/benchmarks/__init__.py
  thunder/benchmarks/targets.py
Labels: benchmarking, hf-transformers, huggingface, peft

#1721 TE: update for TE release_v2.0 support
  thunder/executors/transformer_engineex.py
  thunder/tests/distributed/test_ddp.py
  thunder/tests/distributed/test_fsdp.py
  thunder/tests/test_transformer_engine_executor.py
Labels: TransformerEngine

#1748 numpy 2.0
  requirements/base.txt
  requirements/notebooks.txt
  requirements/test.txt
Labels: dependencies

#1746 Adds a benchmark of MoE layer with deepseek-ai/DeepSeek-R1 config
  thunder/benchmarks/__init__.py
  thunder/benchmarks/targets.py
Labels: benchmarking

#1719 Add benchmark isolation option
  docs/source/intermediate/benchmarking.rst
  thunder/benchmarks/conftest.py
Labels: documentation, benchmarking

#1767 Mark `test_vjp_correctness_sdpa_manual` with non-strict xfail instead of version check
  thunder/tests/opinfos.py
  thunder/tests/test_grad.py
Labels: ci / tests, sdpa

#1765 Add fusion_type compile option for controlling the fusion logic
  thunder/dynamo/compiler.py
  thunder/executors/data_dependent_partition.py
  thunder/tests/test_nvfuser.py
  thunder/tests/test_nvfuser_remat.py
Labels: fusion logic

#1790 Optionally use shared memory pool in CUDAGraphs Transform
  thunder/tests/test_transforms.py
  thunder/transforms/cudagraph.py
Labels: cudagraphs

#1797 Fix implementation of strides computation in cuDNN executor
  thunder/executors/cudnnex.py
  thunder/tests/test_cudnn_executor.py
Labels: cudnn, executors

#1787 Fix tensor.to
  thunder/tests/opinfos.py
  thunder/tests/test_core.py
  thunder/torch/__init__.py
Labels: operators, testing
