Repository Lightning-AI/lightning-thunder, pull requests merged in 2025-06, with the labels that each got.

#2156 TE: update test to be more stable
  thunder/tests/test_transformer_engine_executor.py
Labels: TransformerEngine

#2143 Fix autodiff joint trace dataflow and in-place ops in higher order functions
  thunder/transforms/autodiff.py
Labels: autograd, jit

#2185 Add docstrings for recipes
  docs/source/index.rst
  docs/source/reference/recipes/index.rst
  thunder/recipes/base.py
  thunder/recipes/hf_transformers.py
Labels: documentation, lightning-l1

#2135 `prims.where` ignores shape/device of `pred` if it's a CPU scalar tensor
  thunder/core/prims.py
  thunder/tests/opinfos.py
Labels: operators

#2199 default to hf recipe in thunder.compile for hf models
  thunder/__init__.py
  thunder/core/recipe.py
  thunder/recipes/base.py
  thunder/recipes/hf_transformers.py
Labels: lightning-l1

#2210 Add `bitwise_left_shift` and `bitwise_right_shift`
  thunder/clang/__init__.py
  thunder/core/prims.py
  thunder/core/proxies.py
  thunder/executors/nvfuserex_impl.py
  thunder/executors/torchex.py
  thunder/tests/opinfos.py
  thunder/torch/__init__.py
  thunder/torch/default_torch_ops.py
Labels: operators

#2211 [thunderfx] Avoid split at `Tensor.__eq__` by registering it in `thunder.torch`
  thunder/torch/__init__.py
Labels: thunderfx

#2208 fixed installing NCCL for CUDA
  .azure/gpu-tests.yml
  dockers/ubuntu-cuda/Dockerfile
Labels: docker, ci

#2174 Only register cudnn executor if it is available
  thunder/executors/cudnn_layernormex.py
  thunder/executors/cudnn_sdpa.py
  thunder/executors/cudnnex.py
  thunder/tests/test_cudnn_executor.py
  thunder/tests/test_extend.py
  thunder/tests/test_recipes.py
Labels: lightning-l1

#2235 install cudnn in quickstarts
  .github/run-benchmark-as-lit-jobs.py
  examples/quickstart/requirements.txt
Labels: ci

#2249 bump: OS versions for CI
  .github/workflows/ci-testing.yml
Labels: ci

#2171 Support converting SymTypes Node to input proxy
  thunder/dynamo/utils.py
  thunder/tests/test_dynamo.py
  thunder/torch/__init__.py
Labels: thunderfx

#2222 TE: fix related to delayed forward-backward split
  thunder/core/trace.py
  thunder/executors/torch_autograd.py
  thunder/executors/transformer_engineex.py
  thunder/tests/test_transformer_engine_executor.py
  thunder/transforms/autodiff.py
Labels: autograd, TransformerEngine

#2268 Remove F811 from ignore rules
  pyproject.toml
  thunder/__init__.py
  thunder/benchmarks/__init__.py
  thunder/distributed/tensor_parallel/common.py
  thunder/plugins/reduce_overhead.py
  thunder/tests/distributed/test_dtensor.py
  thunder/tests/test_grad.py
  thunder/tests/test_jit_general.py
  thunder/tests/test_recipes.py
  thunder/tests/test_transformer_engine_executor.py
  thunder/tests/test_transforms.py
  thunder/torch/experimental/dtensor_codeutils.py
  thunder/torch/experimental/dtensor_torch_and_prims.py
  thunder/torch/experimental/dtensor_utils.py
  thunder/transforms/autodiff.py
  thunder/transforms/qlora.py
Labels: install, code health
