Repository Lightning-AI/lightning-thunder, pull requests merged in 2025-05, with the labels that each got.

#2011 ci: run quickstart as Lightning jobs
  .github/run-quickstart-as-lit-jobs.py
  .github/workflows/ci-quickstart.yml
Labels: ci

#2020 move model to default device if it's not there
  .github/run-quickstart-as-lit-jobs.py
  .github/workflows/ci-quickstart.yml
  examples/quickstart/hf_bert.py
  examples/quickstart/hf_llm.py
  examples/quickstart/requirements.txt
  examples/quickstart/vit_hf.py
Labels: ci

#1949 Remove the `torchcompile_cat` executor from the default executor set
  thunder/__init__.py
Labels: executors, nvfuser, performance

#2028 ci: try Slack notifications
  .github/load-quickstart-report.py
  .github/run-quickstart-as-lit-jobs.py
  .github/workflows/ci-quickstart.yml
  .gitignore
Labels: ci, lightning-l1

#2019 Check `last_backward_traces` availability
  thunder/dynamo/report.py
Labels: thunderfx

#2032 switch sphinxcontrib fulltoc to cleaned setup.cfg version
  requirements/docs.txt
Labels: dependencies

#2034 chore(ci): improve slack msg readability
  .github/load-quickstart-report.py
  .github/workflows/ci-quickstart.yml
Labels: ci, lightning-l1

#2030 Fix TransformerEngine executor for all recipes
  thunder/executors/transformer_engineex.py
  thunder/tests/test_transformer_engine_executor.py
Labels: executors, TransformerEngine

#2046 fix check_trace error messages
  thunder/dev_utils/check_trace.py
Labels: lightning-l1

#2044 Re-enable tests for delayed scaling and trace checks
  thunder/tests/test_transformer_engine_executor.py
Labels: testing, TransformerEngine

#2050 add snowballstemmer with < 3 to doc requirements
  requirements/docs.txt
Labels: dependencies

#2053 ci: reduce running linters
  .github/workflows/ci-checks.yml
Labels: ci

#2035 [ThunderFX] Falls back to inductor when the fwd+bwd of a Node fails
  thunder/core/pytree.py
  thunder/dynamo/utils.py
  thunder/tests/test_dynamo.py
Labels: operators, autograd, thunderfx

#2064 quickstart performance analysis for HF models
  .github/run-benchmark_hf-as-lit-jobs.py
  .github/workflows/benchmark_hf.yml
  .gitignore
  README.md
  thunder/benchmarks/benchmark_hf.py
Labels: ci, lightning-l1

#2078 fix install Thunder in jobs
  .github/run-benchmark-as-lit-jobs.py
  .github/run-quickstart-as-lit-jobs.py
  .github/workflows/ci-benchmark.yml
  .github/workflows/ci-quickstart.yml
Labels: ci

#2101 ci: simplify GPU config
  .azure/docker-build.yml
  .azure/gpu-tests.yml
  .azure/notebook-runs.yml
Labels: docker, ci

#2106 docker: fix compile PT from source
  .azure/docker-build.yml
  dockers/ubuntu-cuda/Dockerfile
Labels: docker, ci

#2108 ci/gpu: bump to new images
  .azure/gpu-tests.yml
  .azure/notebook-runs.yml
Labels: ci

#2062 Makes the default optimizer on dynamo-segmented graph and handles OOM
  thunder/dynamo/benchmark_utils.py
  thunder/dynamo/report.py
  thunder/dynamo/utils.py
Labels: reporting

#2130 fix missing images when released on PyPI
  pyproject.toml
Labels: install
