Repository Lightning-AI/lightning-thunder, pull requests merged in 2025-04, with the labels that each got.

#1845 Add an option for skipping nvFuser wrapper cache
  thunder/executors/nvfuserex_impl.py
Labels: nvfuser

#1899 Use adaptive_autorange to mitigate possible instability in benchmark
  docs/source/conf.py
  thunder/dynamo/benchmark_utils.py
  thunder/dynamo/report.py
  thunder/tests/test_dynamo.py
Labels: documentation, benchmarking, reporting

#1967 track main for check-schema
  .github/workflows/ci-checks.yml
Labels: ci

#1769 Remove requires_grad specification from meta functions
  thunder/core/prims.py
  thunder/tests/test_grad.py
Labels: autograd

#1987 drop stale bot
  .github/stale.yml
Labels: ci

#1977 Modernize `pyproject.toml` and `setup.py`
  MANIFEST.in
  pyproject.toml
  requirements/base.txt
  setup.py
  thunder/__about__.py
Labels: dependencies, install

#1995 Remove temporarily `license-files`
  pyproject.toml
Labels: install

#1997 add packaging dependency for building and publishing
  .github/workflows/release-nightly.yml
  .github/workflows/release-pypi.yml
  dockers/ubuntu-cuda/Dockerfile
  requirements/devel.txt
Labels: dependencies, docker, ci

#1993 bump: use the latest PT 2.7
  .azure/docker-build.yml
  .azure/gpu-tests.yml
  .azure/notebook-runs.yml
Labels: docker, ci

#2003 Documentation fixes
  README.md
  docs/source/advanced/contrib_thunder.rst
  docs/source/advanced/inside_thunder.rst
  docs/source/basic/inspecting_traces.rst
  docs/source/basic/sharp_edges.rst
  docs/source/index.rst
  docs/source/intermediate/additional_executors.rst
  notebooks/thunder_trace_intro.ipynb
  thunder/core/module.py
Labels: documentation

#1959 Apply update_aliases to viewed input
  thunder/__init__.py
  thunder/core/update_aliases.py
  thunder/tests/test_update_aliases.py
Labels: in-place
