Repository Lightning-AI/lightning-thunder, pull requests merged in 2025-07, with the labels that each got.

#2303 Fix CI benchmarks
  .github/run-benchmark-as-lit-jobs.py
Labels: ci

#2276 skip complex dtype tensor from `aminmax`
  thunder/dynamo/utils.py
Labels: thunderfx

#2281 Extend thunder.jit coverage on HF models
  .github/load-jit-coverage-report.py
  .github/run-jit-coverage-as-lit-studios.py
  .github/workflows/ci-jit-coverage.yml
  examples/coverage/all.txt
  examples/coverage/jit_coverage_hf.py
  examples/coverage/requirements.txt
Labels: ci

#2254 Add PEFT benchmarking script in `thunder/benchmarks`
  requirements/devel.txt
  thunder/benchmarks/benchmark_peft.py
Labels: dependencies

#2309 Improve reporting from thunder.jit coverage CI job
  .github/run-jit-coverage-as-lit-studios.py
  .github/workflows/ci-jit-coverage.yml
Labels: ci

#2318 Add scalar tensor input to full_sample_generator
  thunder/tests/opinfos.py
  thunder/tests/test_ops.py
Labels: testing

#2320 Run TE tests in CI
  .github/run-transformer-engine-tests-as-lit-jobs.py
  .github/workflows/ci-transformer-engine-tests.yml
Labels: ci

#2217 Add ops for HF transformers
  thunder/dynamo/utils.py
  thunder/tests/test_dynamo.py
  thunder/torch/__init__.py
  thunder/torch/default_torch_ops.py
Labels: operators

#2327 Remove external logger dependency
  requirements/devel.txt
  thunder/benchmarks/benchmark_peft.py
Labels: dependencies

#2314 Relax inplace sanity check
  thunder/core/transform_common.py
  thunder/tests/test_inplace_copy.py
  thunder/tests/test_update_aliases.py
Labels: nvfuser, transforms, in-place

#2052 Make alias updating the default in-place operator approach
  thunder/__init__.py
  thunder/core/functionalization.py
  thunder/core/update_aliases.py
  thunder/tests/test_inplace_functionalization.py
  thunder/tests/test_networks.py
  thunder/tests/test_ops.py
Labels: in-place

#2352 fix docker sanity check
  .azure/docker-build.yml
Labels: docker, ci

#2238 bump bitsandbytes from 0.42.0 to 0.46.1
  requirements/test.txt
  thunder/tests/test_networks.py
Labels: dependencies

#2368 Remove functionalization path
  docs/source/reference/core/functionalization.rst
  docs/source/reference/core/index.rst
  thunder/__init__.py
  thunder/benchmarks/benchmark_hf.py
  thunder/core/functionalization.py
  thunder/core/update_aliases.py
  thunder/tests/test_inplace_functionalization.py
  thunder/tests/test_jit_general.py
  thunder/tests/test_update_aliases.py
  thunder/torch/__init__.py
  thunder/torch/default_torch_ops.py
Labels: documentation
