Repository Lightning-AI/lightning-thunder, pull requests merged in 2025-08, with the labels that each got.

#2329 Support `torch.square` natively
  thunder/tests/opinfos.py
  thunder/torch/__init__.py
  thunder/torch/default_torch_ops.py
Labels: operators

#2232 Adds save_thunderfx_repros to save scripts for all the subgraphs and optionally save fusion region and traces
  thunder/dynamo/report.py
Labels: ux

#2410 deps: pin `cuda-python >=12.0, <13.0.0`
  .azure/notebook-runs.yml
  requirements/notebooks.txt
Labels: dependencies, ci

#2413 chore: bump Torch 2.8
  .azure/gpu-tests.yml
  .azure/notebook-runs.yml
Labels: ci

#2395 Simplify the argsort support
  thunder/clang/__init__.py
  thunder/core/prims.py
  thunder/core/transforms.py
  thunder/executors/nvfuserex_impl.py
  thunder/executors/torchex.py
  thunder/tests/opinfos.py
  thunder/torch/__init__.py
Labels: operators

#2415 ci: reinstall correct torch dependencies
  .github/workflows/ci-testing.yml
  requirements/devel.txt
Labels: dependencies, ci

#2383 [dtensor] add reshape prim and grad rule
  thunder/executors/nvfuserex_impl.py
  thunder/tests/distributed/test_dtensor.py
  thunder/torch/experimental/dtensor_torch_and_prims.py
Labels: nvfuser, DTensor

#2414 re-enable cuda-python nb
  notebooks/extend_thunder_with_cuda_python.ipynb
  requirements/notebooks.txt
Labels: dependencies

#2443 try to fix te ci
  .github/run-transformer-engine-tests-as-lit-jobs.py
Labels: ci

#2141 Diffuser test
  .azure/gpu-coverage.yml
  .github/workflows/coverage_test.yml
  requirements/coverage.txt
  requirements/test.txt
  thunder/tests/coverage_tests/__init__.py
  thunder/tests/coverage_tests/test_coverage_hf_diffusers.py
  thunder/tests/coverage_tests/test_coverage_trace.py
Labels: dependencies, ci

#2451 require PyTorch 2.7
  requirements/base.txt
Labels: dependencies

#2466 fix `F822` undefined-export
  pyproject.toml
  thunder/tests/distributed/helper.py
Labels: install, code health

#2172 Return tuple of 3 `None`s when `try_and_log_benchmark` fails
  thunder/dynamo/benchmark_utils.py
Labels: thunderfx

#2483 convert transformer-engine to lit CI
  .github/run-transformer-engine-tests-as-lit-jobs.py
  .github/workflows/ci-transformer-engine-tests.yml
  .lightning/workflows/all-tests.yaml
  .lightning/workflows/notebooks.yaml
  .lightning/workflows/transformer-engine.yaml
Labels: ci

#2382 [DTensor] Add prims for dtype conversion and broadcasting
  thunder/executors/nvfuserex_impl.py
  thunder/tests/distributed/test_dtensor.py
  thunder/torch/experimental/dtensor_torch_and_prims.py
Labels: nvfuser, DTensor
