Repository Lightning-AI/lightning-thunder, pull requests merged in 2025-03, with the labels that each got.

#1825 TE may raise a TypeError with retain_grad
  thunder/tests/test_transformer_engine_executor.py
Labels: TransformerEngine

#1843 Improve cache lookup overheads in FusionDefinitionWrapper
  thunder/executors/nvfuserex_impl.py
Labels: nvfuser

#1846 Use THUNDER_ANNOTATE_TRACES for enabling NVTX annotations with annotate_for_profile
  thunder/core/profile.py
Labels: profiling

#1838 TE: don't compute wgrad when weights are frozen
  thunder/distributed/prims.py
  thunder/executors/transformer_engineex.py
  thunder/tests/test_transformer_engine_executor.py
Labels: TransformerEngine

#1841 refactoring `Proxy.__init__`'s logic to get `prefix`
  thunder/core/baseutils.py
  thunder/core/proxies.py
Labels: tracing architecture

#1836 Update cuDNN Frontend version to 1.10.0
  .azure/docker-build.yml
  .azure/gpu-tests.yml
  dockers/ubuntu-cuda/Dockerfile
Labels: docker, cudnn, ci

#1876 Update SDPA API in the nvFuser executor
  thunder/core/dtypes.py
  thunder/executors/nvfuserex_impl.py
  thunder/tests/test_nvfuser.py
Labels: nvfuser, sdpa

#1875 add custom grad function for softplus
  thunder/core/transforms.py
  thunder/tests/opinfos.py
Labels: operators, autograd

#1888 bump GPU distributed timeout
  .azure/gpu-tests.yml
Labels: ci

#1780 Introduce update_aliases
  thunder/__init__.py
  thunder/core/prims.py
  thunder/core/rematerialization.py
  thunder/core/transforms.py
  thunder/core/update_aliases.py
  thunder/executors/nvfuserex_impl.py
  thunder/executors/torchex.py
  thunder/tests/test_update_aliases.py
Labels: operators, in-place

#1895 bump CUDA `12.6.3`
  .azure/docker-build.yml
  .azure/gpu-tests.yml
  .azure/notebook-runs.yml
  dockers/ubuntu-cuda/Dockerfile
Labels: docker, ci

#1903 New README v0
  README.md
  docs/source/_static/images/how_it_works.png
  docs/source/_static/images/pretrain_perf.png
  examples/quickstart/hf_llm.py
  thunder/__init__.py
  thunder/recipes/hf_transformers.py
Labels: documentation

#1911 feat: bump transformers to 4.50.2
  dockers/ubuntu-cuda/Dockerfile
  requirements/test.txt
  thunder/tests/test_networks.py
  thunder/tests/test_torch_compile_executor.py
Labels: dependencies, docker, ci
